//
package proyectoFinal;
//
import java.io.IOException;
import javax.swing.JOptionPane;
//
public class VentanaRetiro extends javax.swing.JFrame {

    public VentanaRetiro() {
        initComponents();
        long cuentaIngresada;
        cuentaIngresada = VentanaIngreso.getCuentaIngresada();
        cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();
        try {
            jLCantidadMostrarSaldo.setText("$ "+cuentasAP.regresoDineroCuenta(cuentaIngresada));
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPSaldo = new javax.swing.JPanel();
        jLMostrarSaldo = new javax.swing.JLabel();
        jPCantidadSaldo = new javax.swing.JPanel();
        jLCantidadMostrarSaldo = new javax.swing.JLabel();
        jPRetirar = new javax.swing.JPanel();
        jLRetirar = new javax.swing.JLabel();
        jTFCantidadRetirar = new javax.swing.JTextField();
        jBContinuar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jPSaldo.setBackground(new java.awt.Color(0, 153, 255));

        jLMostrarSaldo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLMostrarSaldo.setText("Su saldo es de:");

        javax.swing.GroupLayout jPSaldoLayout = new javax.swing.GroupLayout(jPSaldo);
        jPSaldo.setLayout(jPSaldoLayout);
        jPSaldoLayout.setHorizontalGroup(
            jPSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSaldoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLMostrarSaldo)
                .addGap(34, 34, 34))
        );
        jPSaldoLayout.setVerticalGroup(
            jPSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMostrarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPCantidadSaldo.setBackground(new java.awt.Color(0, 153, 255));

        jLCantidadMostrarSaldo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLCantidadMostrarSaldo.setText("$$$$$$$$$$$$");

        javax.swing.GroupLayout jPCantidadSaldoLayout = new javax.swing.GroupLayout(jPCantidadSaldo);
        jPCantidadSaldo.setLayout(jPCantidadSaldoLayout);
        jPCantidadSaldoLayout.setHorizontalGroup(
            jPCantidadSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCantidadSaldoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLCantidadMostrarSaldo)
                .addGap(34, 34, 34))
        );
        jPCantidadSaldoLayout.setVerticalGroup(
            jPCantidadSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCantidadMostrarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPRetirar.setBackground(new java.awt.Color(0, 153, 255));

        jLRetirar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLRetirar.setText("Cantidad:");

        javax.swing.GroupLayout jPRetirarLayout = new javax.swing.GroupLayout(jPRetirar);
        jPRetirar.setLayout(jPRetirarLayout);
        jPRetirarLayout.setHorizontalGroup(
            jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRetirarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLRetirar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPRetirarLayout.setVerticalGroup(
            jPRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLRetirar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jTFCantidadRetirar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTFCantidadRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantidadRetirarActionPerformed(evt);
            }
        });

        jBContinuar.setBackground(new java.awt.Color(0, 204, 0));
        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(new java.awt.Color(255, 0, 51));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBRegresar.setBackground(new java.awt.Color(255, 191, 0));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFCantidadRetirar)
                    .addComponent(jPCantidadSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBContinuar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jBRegresar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCancelar, jBContinuar, jBRegresar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPCantidadSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCantidadRetirar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPRetirar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCancelar, jBContinuar, jBRegresar});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventanaMenu = new VentanaMenu();
        ventanaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        jTFCantidadRetirar.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed
        // TODO add your handling code here:
        String cantidadS;
        boolean cantidadNumero;
        cantidadS = jTFCantidadRetirar.getText();
        if (!cantidadS.equals("")) {
            try {
                Double.parseDouble(cantidadS);
                //System.out.println("La cantidad ingresada es un número"); //(Temporal)
                cantidadNumero = true;
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Solo se permite ingresar números.");
                cantidadNumero = false;
            }
            if (cantidadNumero) {
                double cantidad;
                cantidad = Double.parseDouble(cantidadS);
                if (cantidad >= 50) {
                    long cuentaIngresada;
                    cuentaIngresada = VentanaIngreso.getCuentaIngresada();
                    cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();
                    try {
                        cuentasAP.retiroEfectivo(cuentaIngresada, cantidad);
                        //
                        VentanaRetiro ventanaRetiro = new VentanaRetiro();
                        ventanaRetiro.setVisible(true);
                        this.dispose();
                    } catch (IOException ex) {
                        System.out.println("Error: " + ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Solo se permiten retiros mayor o igual a $50.");
                }
            }
            jTFCantidadRetirar.setText("");
        }
    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jTFCantidadRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantidadRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantidadRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLCantidadMostrarSaldo;
    private javax.swing.JLabel jLMostrarSaldo;
    private javax.swing.JLabel jLRetirar;
    private javax.swing.JPanel jPCantidadSaldo;
    private javax.swing.JPanel jPRetirar;
    private javax.swing.JPanel jPSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFCantidadRetirar;
    // End of variables declaration//GEN-END:variables
}
