//
package proyectoFinal;
//
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//
public class VentanaMenu extends javax.swing.JFrame {
    
    public VentanaMenu() {
        initComponents();
        long cuentaIngresada;
        cuentaIngresada = VentanaIngreso.getCuentaIngresada();
        cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();        
        try {
            jLBienvedidaNombre.setText("Bienvenido(a) " + cuentasAP.regresoNombreCuenta(cuentaIngresada));
            jLCiudad.setText(cuentasAP.regresoCiudadCuenta(cuentaIngresada));
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLBienvedidaNombre = new javax.swing.JLabel();
        jLCiudad = new javax.swing.JLabel();
        jBSalir2 = new javax.swing.JButton();
        jBConsultarSaldo = new javax.swing.JButton();
        jBCambiarNip = new javax.swing.JButton();
        jBRetirarEfectivo = new javax.swing.JButton();
        jBTransferencia = new javax.swing.JButton();
        jBImprimirTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLBienvedidaNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLBienvedidaNombre.setText("Bienvenido(a)");

        jLCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLCiudad.setText("Ciudad");

        jBSalir2.setBackground(new java.awt.Color(51, 51, 51));
        jBSalir2.setForeground(new java.awt.Color(255, 255, 255));
        jBSalir2.setText("Salir");
        jBSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalir2ActionPerformed(evt);
            }
        });

        jBConsultarSaldo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jBConsultarSaldo.setText("Consultar Saldo");
        jBConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarSaldoActionPerformed(evt);
            }
        });

        jBCambiarNip.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jBCambiarNip.setText("Cambiar NIP");
        jBCambiarNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCambiarNipActionPerformed(evt);
            }
        });

        jBRetirarEfectivo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jBRetirarEfectivo.setText("Retirar Efectivo");
        jBRetirarEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetirarEfectivoActionPerformed(evt);
            }
        });

        jBTransferencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jBTransferencia.setText("Transferencia Bancaria");
        jBTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransferenciaActionPerformed(evt);
            }
        });

        jBImprimirTrans.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jBImprimirTrans.setText("Imprimir trasnsacciones");
        jBImprimirTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCiudad)
                                    .addComponent(jLBienvedidaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 309, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBImprimirTrans)
                            .addComponent(jBTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBRetirarEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCambiarNip, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCambiarNip, jBConsultarSaldo, jBImprimirTrans, jBRetirarEfectivo, jBTransferencia});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLBienvedidaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jBConsultarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCambiarNip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBRetirarEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImprimirTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCambiarNip, jBConsultarSaldo, jBImprimirTrans, jBRetirarEfectivo, jBTransferencia});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalir2ActionPerformed
        // TODO add your handling code here:
        VentanaIngreso ventanaIngreso = new VentanaIngreso();
        ventanaIngreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBSalir2ActionPerformed

    private void jBConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarSaldoActionPerformed
        // TODO add your handling code here:
        VentanaConsultarSaldo ventanaConsultarSaldo = new VentanaConsultarSaldo();
        ventanaConsultarSaldo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBConsultarSaldoActionPerformed

    private void jBCambiarNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCambiarNipActionPerformed
        // TODO add your handling code here:
        VentanaCambioNip ventanaCambioNip = new VentanaCambioNip();
        ventanaCambioNip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCambiarNipActionPerformed

    private void jBRetirarEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetirarEfectivoActionPerformed
        // TODO add your handling code here:
        VentanaRetiro ventanaRetiro = new VentanaRetiro();
        ventanaRetiro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRetirarEfectivoActionPerformed

    private void jBTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransferenciaActionPerformed
        // TODO add your handling code here:
        VentanaTransferencia ventanaTransferencia = new VentanaTransferencia();
        ventanaTransferencia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBTransferenciaActionPerformed

    private void jBImprimirTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirTransActionPerformed
        // TODO add your handling code here:
        boolean existenciaTransferencia=false;
        long cuentaIngresada;
        cuentaIngresada = VentanaIngreso.getCuentaIngresada();
        cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();
        try {           
            existenciaTransferencia = cuentasAP.buscarArchivoTransferencia(cuentaIngresada);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
        if (existenciaTransferencia) {
            try {
                VentanaImprmirTransacciones ventanaImprmirTransacciones = new VentanaImprmirTransacciones();
                ventanaImprmirTransacciones.setVisible(true);
                this.dispose();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"No ha realizado alguna transacción");
        }
    }//GEN-LAST:event_jBImprimirTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCambiarNip;
    private javax.swing.JButton jBConsultarSaldo;
    private javax.swing.JButton jBImprimirTrans;
    private javax.swing.JButton jBRetirarEfectivo;
    private javax.swing.JButton jBSalir2;
    private javax.swing.JButton jBTransferencia;
    private javax.swing.JLabel jLBienvedidaNombre;
    private javax.swing.JLabel jLCiudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
