//
package proyectoFinal;
//
import java.io.IOException;
import javax.swing.JOptionPane;
//
public class VentanaTransferencia extends javax.swing.JFrame {

    public VentanaTransferencia() {
        initComponents();
        long cuentaIngresada;
        cuentaIngresada = VentanaIngreso.getCuentaIngresada();
        cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();        
        try {           
            jLCantidadMostrarSaldo.setText("$ "+cuentasAP.regresoDineroCuenta(cuentaIngresada));
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPSaldo = new javax.swing.JPanel();
        jLMostrarSaldo = new javax.swing.JLabel();
        jPCantidadSaldo = new javax.swing.JPanel();
        jLCantidadMostrarSaldo = new javax.swing.JLabel();
        jPNumeroCuenta1 = new javax.swing.JPanel();
        jLNumeroCuenta1 = new javax.swing.JLabel();
        jPNumeroCuenta2 = new javax.swing.JPanel();
        jLNumeroCuenta2 = new javax.swing.JLabel();
        jTFNumeroCuenta1 = new javax.swing.JTextField();
        jTFNumeroCuenta2 = new javax.swing.JTextField();
        jPCantidadDepositar = new javax.swing.JPanel();
        jLCantidadDepositar = new javax.swing.JLabel();
        jTFCantidadDepositar = new javax.swing.JTextField();
        jBContinuar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cajero Automático");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jPSaldo.setBackground(new java.awt.Color(0, 153, 255));

        jLMostrarSaldo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLMostrarSaldo.setText("Su saldo es de:");

        javax.swing.GroupLayout jPSaldoLayout = new javax.swing.GroupLayout(jPSaldo);
        jPSaldo.setLayout(jPSaldoLayout);
        jPSaldoLayout.setHorizontalGroup(
            jPSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSaldoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLMostrarSaldo)
                .addGap(34, 34, 34))
        );
        jPSaldoLayout.setVerticalGroup(
            jPSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMostrarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPCantidadSaldo.setBackground(new java.awt.Color(0, 153, 255));

        jLCantidadMostrarSaldo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLCantidadMostrarSaldo.setText("$$$$$$$$$$$$");

        javax.swing.GroupLayout jPCantidadSaldoLayout = new javax.swing.GroupLayout(jPCantidadSaldo);
        jPCantidadSaldo.setLayout(jPCantidadSaldoLayout);
        jPCantidadSaldoLayout.setHorizontalGroup(
            jPCantidadSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCantidadSaldoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLCantidadMostrarSaldo)
                .addGap(34, 34, 34))
        );
        jPCantidadSaldoLayout.setVerticalGroup(
            jPCantidadSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCantidadMostrarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPNumeroCuenta1.setBackground(new java.awt.Color(0, 153, 255));

        jLNumeroCuenta1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLNumeroCuenta1.setText("Ingrese número de cuenta:");

        javax.swing.GroupLayout jPNumeroCuenta1Layout = new javax.swing.GroupLayout(jPNumeroCuenta1);
        jPNumeroCuenta1.setLayout(jPNumeroCuenta1Layout);
        jPNumeroCuenta1Layout.setHorizontalGroup(
            jPNumeroCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNumeroCuenta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNumeroCuenta1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNumeroCuenta1Layout.setVerticalGroup(
            jPNumeroCuenta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLNumeroCuenta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPNumeroCuenta2.setBackground(new java.awt.Color(0, 153, 255));

        jLNumeroCuenta2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLNumeroCuenta2.setText("Confirmar número de cuenta:");

        javax.swing.GroupLayout jPNumeroCuenta2Layout = new javax.swing.GroupLayout(jPNumeroCuenta2);
        jPNumeroCuenta2.setLayout(jPNumeroCuenta2Layout);
        jPNumeroCuenta2Layout.setHorizontalGroup(
            jPNumeroCuenta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNumeroCuenta2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLNumeroCuenta2)
                .addGap(34, 34, 34))
        );
        jPNumeroCuenta2Layout.setVerticalGroup(
            jPNumeroCuenta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLNumeroCuenta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jTFNumeroCuenta1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTFNumeroCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroCuenta1ActionPerformed(evt);
            }
        });

        jTFNumeroCuenta2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTFNumeroCuenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroCuenta2ActionPerformed(evt);
            }
        });

        jPCantidadDepositar.setBackground(new java.awt.Color(0, 153, 255));

        jLCantidadDepositar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLCantidadDepositar.setText("Cantidad:");

        javax.swing.GroupLayout jPCantidadDepositarLayout = new javax.swing.GroupLayout(jPCantidadDepositar);
        jPCantidadDepositar.setLayout(jPCantidadDepositarLayout);
        jPCantidadDepositarLayout.setHorizontalGroup(
            jPCantidadDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCantidadDepositarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLCantidadDepositar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPCantidadDepositarLayout.setVerticalGroup(
            jPCantidadDepositarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCantidadDepositar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jTFCantidadDepositar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTFCantidadDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCantidadDepositarActionPerformed(evt);
            }
        });

        jBContinuar.setBackground(new java.awt.Color(0, 204, 0));
        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(new java.awt.Color(255, 0, 51));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBRegresar.setBackground(new java.awt.Color(255, 191, 0));
        jBRegresar.setText("Regresar");
        jBRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPNumeroCuenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPNumeroCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPCantidadSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNumeroCuenta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNumeroCuenta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBContinuar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBRegresar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCancelar, jBContinuar, jBRegresar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCantidadSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPNumeroCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumeroCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPNumeroCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumeroCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCantidadDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCancelar, jBContinuar, jBRegresar});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegresarActionPerformed
        // TODO add your handling code here:
        VentanaMenu ventanaMenu = new VentanaMenu();
        ventanaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRegresarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        jTFNumeroCuenta1.setText("");
        jTFNumeroCuenta2.setText("");
        jTFCantidadDepositar.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed
        // TODO add your handling code here:
        String cuenta1S,cuenta2S,cantidadS;
        cuenta1S = jTFNumeroCuenta1.getText();
        cuenta2S = jTFNumeroCuenta2.getText();
        cantidadS = jTFCantidadDepositar.getText();
        cuenta1S = cuenta1S.replace(" ", "");
        cuenta2S = cuenta2S.replace(" ", "");
        if (cuenta1S.equals("") || cuenta2S.equals("") || cantidadS.equals("")) {
            JOptionPane.showMessageDialog(null, "Recuerde llenar todos los campos.");
        }else{
            boolean soloNumeros;
            try {
                Long.parseLong(cuenta1S);
                Long.parseLong(cuenta2S);
                Double.parseDouble(cantidadS);
                soloNumeros = true;
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Solo se permite ingresar números.");
                soloNumeros = false;
            }
            if (soloNumeros) {
                long cuentaIngresada;
                cuentaIngresada = VentanaIngreso.getCuentaIngresada();
                long cuentaATransferir;
                cuentaATransferir = Long.parseLong(cuenta1S);
                if (cuentaIngresada==cuentaATransferir) {
                    JOptionPane.showMessageDialog(null, "No se puede realizar la transferencia.\nLa cuenta a la que trata de depositar es la suya.");
                    jBCancelarActionPerformed(evt);
                }else {
                    if (cuenta1S.equals(cuenta2S)) {
                        cuentasAccionesPrincipales cuentasAP = new cuentasAccionesPrincipales();
                        try {
                            boolean hacerTranferencia1;
                            hacerTranferencia1 = cuentasAP.buscarCuentasMostrarMensaje(cuentaATransferir);
                            if (hacerTranferencia1) {
                                double cantidad;
                                cantidad = Double.parseDouble(cantidadS);
                                if (cantidad > 0) {
                                    try {
                                        boolean hacerTranferencia2;
                                        hacerTranferencia2 = cuentasAP.comprobarTransferencia(cuentaIngresada, cantidad);
                                        if (hacerTranferencia2) {
                                            cuentasAP.realizarTransferencia(cuentaIngresada, cuentaATransferir, cantidad);
                                            //
                                            VentanaTransferencia ventanaTransferencia = new VentanaTransferencia();
                                            ventanaTransferencia.setVisible(true);
                                            this.dispose();
                                        } else {
                                            jTFCantidadDepositar.setText("");
                                        }
                                    } catch (IOException ex) {
                                        System.out.println("Error: " + ex);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Solo se permiten cantidades positivas.");
                                    jTFCantidadDepositar.setText("");
                                }
                            } else {
                                jBCancelarActionPerformed(evt);
                            }
                        } catch (IOException ex) {
                            System.out.println("Error: " + ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Los números de cuenta ingresados no coinciden.");
                        jBCancelarActionPerformed(evt);
                    }
                }
            }else{
                jTFNumeroCuenta1.setText("");
                jTFNumeroCuenta2.setText("");
                jTFCantidadDepositar.setText("");
            }
        }
    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jTFCantidadDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCantidadDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCantidadDepositarActionPerformed

    private void jTFNumeroCuenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroCuenta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroCuenta2ActionPerformed

    private void jTFNumeroCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroCuenta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jBRegresar;
    private javax.swing.JLabel jLCantidadDepositar;
    private javax.swing.JLabel jLCantidadMostrarSaldo;
    private javax.swing.JLabel jLMostrarSaldo;
    private javax.swing.JLabel jLNumeroCuenta1;
    private javax.swing.JLabel jLNumeroCuenta2;
    private javax.swing.JPanel jPCantidadDepositar;
    private javax.swing.JPanel jPCantidadSaldo;
    private javax.swing.JPanel jPNumeroCuenta1;
    private javax.swing.JPanel jPNumeroCuenta2;
    private javax.swing.JPanel jPSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFCantidadDepositar;
    private javax.swing.JTextField jTFNumeroCuenta1;
    private javax.swing.JTextField jTFNumeroCuenta2;
    // End of variables declaration//GEN-END:variables
}
